### ISSUE TITLE
stadusrp_getJobsOnline

### ISSUE THREAD

**Issue by Vanheden** [Stadus/Stadus_Scoreboard#1]
`ESX.RegisterServerCallback('stadusrp_getJobsOnline', function(source, cb)`

Crash cause of 

`stadusrp_getJobsOnline`
`TriggerServerCallback => [stadusrp_getJobsOnline] does not exists`

**Comment by ElPumpo** [comment]
It's right here? https://github.com/Stadus/Stadus_Scoreboard/blob/master/scoreboard/server.lua#L53

**Comment by Stadus** [comment]
I think you haven't put the scoreboard after es_extended in server.cfg

**Comment by JaroSound** [comment]
TriggerServerCallback => [stadusrp_getJobsOnline] does not exists

Same problem, my scoreboard is after es_extended
