### ISSUE TITLE
Where do you go to change the hotkey?

### ISSUE THREAD

**Issue by Ashember** [Stadus/Stadus_Scoreboard#12]
So I'd like to move the hotkey to something else, can you please tell me specifically which file I can get it changed in?  Please include the file path

**Comment by norbzy** [comment]
In the Client.lua, look for lines 120-134ish

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)

		if IsControlJustReleased(0, Keys['F11']) and IsInputDisabled(0) then
			ToggleScoreBoard()
			Citizen.Wait(200)

		-- D-pad up on controllers works, too!
		elseif IsControlJustReleased(0, 172) and not IsInputDisabled(0) then
			ToggleScoreBoard()
			Citizen.Wait(200)
		end
	end
end)
