### ISSUE TITLE
Error image on game.

### ISSUE THREAD

**Issue by hnomkeng** [Stadus/Stadus_Scoreboard#4]
![image](https://user-images.githubusercontent.com/9112684/39819111-cd82e0e2-53cc-11e8-92fc-7f4334782919.png)

**Comment by HumanTree92** [comment]
You didn't follow the guide on how to install this. https://forum.fivem.net/t/release-esx-custom-scoreboard-with-jobs-online/84767/67 Go here & read through the comments.
